apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: alertmanager-routes
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  hosts:
  - "alert.jiminhome.shop"

  gateways:
  - blog-system/blog-gateway

  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: alertmanager.monitoring.svc.cluster.local
        port:
          number: 9093
    timeout: 30s
