apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-routes
  namespace: monitoring
  labels:
    app: grafana
spec:
  hosts:
  - "grafana.jiminhome.shop"

  gateways:
  - blog-system/blog-gateway

  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
        port:
          number: 80
    timeout: 30s
