apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hubble-ui-routes
  namespace: monitoring
  labels:
    app: hubble-ui
spec:
  hosts:
  - "hubble.jiminhome.shop"

  gateways:
  - blog-system/blog-gateway

  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: hubble-ui.kube-system.svc.cluster.local  # Hubble UI는 kube-system에 배포됨
        port:
          number: 80
    timeout: 30s
