apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-routes
  namespace: monitoring
  labels:
    app: kiali
spec:
  hosts:
  - "kiali.jiminhome.shop"

  gateways:
  - blog-system/blog-gateway

  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kiali.istio-system.svc.cluster.local  # Kiali는 istio-system에 배포됨
        port:
          number: 20001
    timeout: 30s
