apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-routes
  namespace: monitoring
  labels:
    app: prometheus
spec:
  hosts:
  - "prom.jiminhome.shop"

  gateways:
  - blog-system/blog-gateway

  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local 
        port:
          number: 9090
    timeout: 30s
