apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-pvc.yaml
  - mysql-circuit-breaker.yaml
  - mysql-exporter.yaml
  - mysql-exporter-sealedsecret.yaml
  - mysql-sealedsecret.yaml
  - mysql-mtls-exception.yaml
