apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - was-rollout.yaml
  - was-service.yaml
  - was-configmap.yaml
  - was-destinationrule.yaml
  - was-retry-timeout.yaml
  - authz-was.yaml
  - github-oauth-sealedsecret.yaml
