apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web-rollout.yaml
  - web-service.yaml
  - web-nginx-config.yaml
  - web-virtualservice.yaml
  - web-destinationrule.yaml
  - authz-web.yaml
