---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgBQIZ+9cOfCi5/ubyIy4ScKrrTf+LBvmjdo0ViE6dCPbiWUiaWdBm64kF9lSgwyiRTw78M9SlAvOrtSXa07atEOB4Nco9ErGHBpIBga5ii2ttPx9RulBjTph9OpFjgYH9oIGohlb8WVgaYtkk2dFKt5c8tShLy+qVm77IMCw3NFh6VJx1KBqCPhgSmePS+y5snhp2KqoNOx/ciCw4lS7Q8KUfCjQulUiB6y9dIMp+KE3eoVg1J3qw9yYen6PI2AdHwEY/iR+59auW+72pJIjtKBHSWKPKBA3ZwjiUSh6cgxX9Syb/YJRJ7NZOV1T0tGtDkyrn3rAbjwH5vOEkB+lkcbjoNXdd25r60uG3UuZB4mTsuCn5aVFrP/JgPK1EmEV6BwNW0575WVSkf6a7IHF5/5dDdwZJT22abQNgzf9y5I9mfhrMXPdIwIwTYpIv1ilP0Yvlr4lhh+wcEa7KdLiD42r3J62UaePH7fKJqlZ06RuPVG09E7htuHhPSwuHfldj/rFmswQ872deiWlkCdURKhyXTVZj7Q/RsAJkRkh3FnjukL65NkYC7fs8vZDtC/xyJfsRG5bfbhnbeniXKq8dxDoZOevVgh95yNaQEHLVhIx9SInxwhrZ9JrAOirmHpNjaM3uDy+bmJSI3MSifYaEf4OWGh+oRg3cscCiWXuPEygh1ZYHqN9yNrBVIbpTzkESg+b7vgY92yaq7YV3sl0nm1GlYMqpTeQsUDVS9zCtbwd/1jgFLAUWs8UAZ4HBgZWF2eu4oGehpoiJAuobTqSVKj+L8YHufbGAx5OSm4rzGrlU6IMcxlz515HUSr9fjfzIYlaq5gS/t7UAmGRQ+6qlsv9b0qijDGAK2eI39PtExOxWzo
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: monitoring
    type: Opaque
