---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: backup-system
spec:
  encryptedData:
    mysql-password: AgBgiNsykWy9u0x86mFz2J5SwhVWpaU0RV2Wx8V+kTyMkUmmuezrYvnuupK2oZDbmd5FBebvqGxAYl8iQAhNUl0E232mNcdUImU2aunAbVDMmDC6Z5OalA8VYancngNC79B5Pw1P+U5CypyJnLcQtZEjdzUMwqI7GAUd9rJeueW0X9/FtFQre7eyo/0hk0h1nkjL85SN+AGnkeay3/07qRCK37lzkzh0BV858OpBrfpO0MneDuFeS0DiaWNCxaSvdPQBIC5UR8TqcY45g5K48EkUmvjisDL8GLPUPsU1b/ufq8u6DRT57/QFj8HkzzAPff2ix5fsLlI9HbzL0C1XWgndG7xxpca5MTGBJBPx8tRSaXoiQDWcvtRD7flVN3h7BNHpBC9RylxlRsOFFah2rHzSwZQpUeuJMIOIE63IWowsMkxRalcoKDh1rI31cy1229d0vqz1So3Vd42qh1mpr4Sg8QWHVSKaU4RVBncxFaB0mEZTSzUepHIdGI2M/L/6KdIJFCy42JUnmYIRD08o9p74k6uWksvgkZhDbA5aLDWElRlGL9g91co9yCZWh4rGI0n77XsNTlbBRabmGZ+5PzoKzY1tBtsTc5gWR38yNXO6rZ/r1ETOtFsgnWb1tnDB+nmgoFyyLpl4RQnQICdICSlmtZjxY+Il/hDmB4CkbT2C9mjmHx4LrnZWJm00FSztvN0oA7K0sYx3aWIbgXUp
    mysql-root-password: AgBqR8lGsUbfYCK5s+DuW+07gV5jLEcc1OkuKKSL5Z1tBOmp+JZDWXxNZeohhVKH2PtbCZE1cJm32hJhOnhD77rIElR/ezDDypP40inydQbm/14O+0HUu8n4EchNFB9W4sB3GdeBth0vNyObYD+PnymRnFcq6vw1xqpaCMCnvJWevI05CTtqUXEgc2sSkNBBuaV1atN5yR5+YM5IvR6Dv9z4aSyVT94kAzvBjBjkkwAVaU6d79p8oWXjZk3tEI5VHJK4oPbRGco4+RADznDz/cpriWZo9fFzKJDrOp5S6Wp2R45jp33addygDByoWJt5nvRRqyJRKUMtNp2N0lVT1kolzCtGKQqqfTw9FzP4vkddDKh9MdEAZYigqqCpv7ZFaz5rqecwfOL/8weqWQrmqYxlbHowaAYGu+c4C/L/AoR1lnkZ9kxvc201MM6nlRaKVApizhDqUBx7uyV94H0WGaC2TcWZpiTRE8yzzHiu3oVK9QDK300ZrftocF9uE3I5g16NKjhqdzlci9Jd1UTNB4cWMJ8eaJNt5HjKJ7hDQ31B79n4gnX+mx0+d9U+SnnPwa4o9KrL3sxaBFCOyozo4K264oe7lUPclQRNKwsF/sdTSYfBE+grRgjnWqBfYhW06bFwG106+eN2hz/na6wt4Q15Bal6iw2enkycxv188vYMs5G0MIvrQv/1WtMv/tfvut9DLY05rEPlgQooZ9Q=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
      name: mysql-secret
      namespace: backup-system
    type: Opaque
